version: "3"

services:
  rufus:
    container_name: rufus
    hostname: rufus
    restart: unless-stopped
    image: rufus
    build:
      context: .
    environment:
      - DOCKER_MODE=True
      - GIT_PYTHON_REFRESH=quiet
    volumes:
      - ./src:/app
      #- ./logs:/app/logs
    #ports:
      #- 8080:8080
